export default {
    DROP_STATE_ON_UNAUTH: 'DROP_STATE_ON_UNAUTH',
    //auth reducer
    SET_AUTH: 'SET_AUTH',
    SET_USER: 'SET_USER',
    //film reducer
    SET_FILMS_LIST: 'SET_FILMS_LIST',
    SET_CURRENT_FILM: 'SET_CURRENT_FILM',
    ADD_FILM_TO_FILM_LIST: 'ADD_FILM_TO_FILM_LIST',
    //producer reducer
    SET_PRODUCERS_LIST: 'SET_PRODUCERS_LIST',
    SET_CURRENT_PRODUCER: 'SET_CURRENT_PRODUCER'
}